language: php
sudo: false
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "hhvm"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "nightly"
    - php: "hhvm"

env:
  - CLOSURE_VERSION: 20161024

services:
  - memcached

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer update --no-interaction --prefer-source

before_script:
  - tests/dl-closure.sh

script:
  - composer validate
  - phpunit --verbose

# vim:ts=2:sw=2:et
